### PR TITLE
Math magicians: Full Website

### PR DESCRIPTION
**Pull request by zainsadaqat**
### In this pull request, I implemented the following:
- Create a website consisting of 3 pages: Home, Calculator, and Quote.
- Use React basic styling
- Use React Routes
- No Linters Errors

### CODE REVIEW

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @zainsadaqat, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Your app consists of three pages and everything looks good.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] README file should have the steps on how to clone the project.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zainsadaqat** [comment]
**REQUIREMENT:** README file should have the steps on how to clone the project.

**ANSWER:** This is not a way to stop the approval for something missing in README and nobody does this as I am in the Microverse program for over 10 weeks now. and all previous code reviewers put this as OPTIONAL if they demand something to add or change in README.

**Review by dasileker — APPROVED** [review]
### **Hi @zainsadaqat,** 

### **Project Approved ✅**

Approved


Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zainsadaqat** [comment]
# Thank you so much @dasileker for approving my pull request!

**Pull request merged**
